name: Create Issue on New Release
on:
  release:
    types:
      - created

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Create Issue
        id: create_issue
        run: |
          # Get the release information
          # Create an issue using the GitHub CLI
          gh issue create --title "New Release" --body "Release Notes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
