name: Create Issue on New Release
on:
  release:
    types:
      - created

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        id: create_issue
        run: |
          # Get the release information
          release_tag="$GITHUB_REF"
          release_title="$GITHUB_EVENT.client_payload.title"
          release_body="$GITHUB_EVENT.client_payload.body"

          # Create an issue using the GitHub CLI
          gh issue create --title "New Release: $release_tag" --body "Release Notes:\n\n$release_title\n\n$release_body"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
